version: "3.9"
services:
  neo4j:
    image: neo4j:5.25
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-pleasechangeme}
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/data
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  evolution:
    build: .
    image: ce-poc:evolution
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    command: ["python", "-m", "src.competitive_evolution"]
    depends_on:
      - neo4j
      - prometheus
volumes:
  neo4j_data: {}
