global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: 'evolution-poc'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

rule_files:
  - alert_rules.yml

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets:
          - pushgateway:9091

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090

  - job_name: 'node'
    static_configs:
      - targets:
          - localhost:9100
